### PR TITLE
Reformatted Source Code and added new features.

### PR DESCRIPTION
**Pull request by michaelrutherford**
Reformatted source code with 8 spaces, removed all tabs, and fixed line indentation. I also added line highlighting functionality as well as the ability to switch freely from tabs to spaces.

### CODE REVIEW

**Comment by zesterer** [comment]
That's a useful thing to do. I started doing this some time back when Journal was new on the scene, but I didn't get round to finishing it.

**Comment by ikeydoherty** [comment]
I've done this once already too :)

**Comment by michaelrutherford** [comment]
Added the feature requested by @Justinzobel in issue #68 .

**Comment by michaelrutherford** [comment]
Added the feature requested by @Justinzobel in issue #44 .

**Pull request merged**
